<?php
/**
 * JobCallbackEvent
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Acaisia Marketplace Client
 *
 * Endpoints for clients - users that want to submit calculations. E.g. someone running an inference request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Acaisia\Marketplace\Model;
use \Acaisia\Marketplace\ObjectSerializer;

/**
 * JobCallbackEvent Class Doc Comment
 *
 * @category Class
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JobCallbackEvent
{
    /**
     * Possible values of this enum
     */
    public const CALLBACK_ALL = 'CALLBACK_ALL';

    public const STATE_RUNNING = 'STATE_RUNNING';

    public const STATE_FINISHED = 'STATE_FINISHED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CALLBACK_ALL,
            self::STATE_RUNNING,
            self::STATE_FINISHED
        ];
    }
}


