<?php
/**
 * JobParametersBlenderEevee
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Acaisia Marketplace Client
 *
 * Endpoints for clients - users that want to submit calculations. E.g. someone running an inference request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Acaisia\Marketplace\Model;

use \ArrayAccess;
use \Acaisia\Marketplace\ObjectSerializer;

/**
 * JobParametersBlenderEevee Class Doc Comment
 *
 * @category Class
 * @description Parameters specifically for a Blender EEVEE render job. Only here as a helper.
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class JobParametersBlenderEevee implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JobParametersBlenderEevee';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'resolution' => '\Acaisia\Marketplace\Model\JobParametersBlenderEeveeResolution',
        'frames' => '\Acaisia\Marketplace\Model\JobParametersBlenderEeveeFrames',
        'taa_render_samples' => 'int',
        'scene_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'resolution' => null,
        'frames' => null,
        'taa_render_samples' => null,
        'scene_url' => 'url'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'resolution' => false,
        'frames' => false,
        'taa_render_samples' => false,
        'scene_url' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'resolution' => 'resolution',
        'frames' => 'frames',
        'taa_render_samples' => 'taa_render_samples',
        'scene_url' => 'scene_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'resolution' => 'setResolution',
        'frames' => 'setFrames',
        'taa_render_samples' => 'setTaaRenderSamples',
        'scene_url' => 'setSceneUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'resolution' => 'getResolution',
        'frames' => 'getFrames',
        'taa_render_samples' => 'getTaaRenderSamples',
        'scene_url' => 'getSceneUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('resolution', $data ?? [], null);
        $this->setIfExists('frames', $data ?? [], null);
        $this->setIfExists('taa_render_samples', $data ?? [], 64);
        $this->setIfExists('scene_url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['resolution'] === null) {
            $invalidProperties[] = "'resolution' can't be null";
        }
        if ($this->container['frames'] === null) {
            $invalidProperties[] = "'frames' can't be null";
        }
        if ($this->container['taa_render_samples'] === null) {
            $invalidProperties[] = "'taa_render_samples' can't be null";
        }
        if (($this->container['taa_render_samples'] > 256)) {
            $invalidProperties[] = "invalid value for 'taa_render_samples', must be smaller than or equal to 256.";
        }

        if (($this->container['taa_render_samples'] < 1)) {
            $invalidProperties[] = "invalid value for 'taa_render_samples', must be bigger than or equal to 1.";
        }

        if ($this->container['scene_url'] === null) {
            $invalidProperties[] = "'scene_url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets resolution
     *
     * @return \Acaisia\Marketplace\Model\JobParametersBlenderEeveeResolution
     */
    public function getResolution()
    {
        return $this->container['resolution'];
    }

    /**
     * Sets resolution
     *
     * @param \Acaisia\Marketplace\Model\JobParametersBlenderEeveeResolution $resolution resolution
     *
     * @return self
     */
    public function setResolution($resolution)
    {
        if (is_null($resolution)) {
            throw new \InvalidArgumentException('non-nullable resolution cannot be null');
        }
        $this->container['resolution'] = $resolution;

        return $this;
    }

    /**
     * Gets frames
     *
     * @return \Acaisia\Marketplace\Model\JobParametersBlenderEeveeFrames
     */
    public function getFrames()
    {
        return $this->container['frames'];
    }

    /**
     * Sets frames
     *
     * @param \Acaisia\Marketplace\Model\JobParametersBlenderEeveeFrames $frames frames
     *
     * @return self
     */
    public function setFrames($frames)
    {
        if (is_null($frames)) {
            throw new \InvalidArgumentException('non-nullable frames cannot be null');
        }
        $this->container['frames'] = $frames;

        return $this;
    }

    /**
     * Gets taa_render_samples
     *
     * @return int
     */
    public function getTaaRenderSamples()
    {
        return $this->container['taa_render_samples'];
    }

    /**
     * Sets taa_render_samples
     *
     * @param int $taa_render_samples taa_render_samples
     *
     * @return self
     */
    public function setTaaRenderSamples($taa_render_samples)
    {
        if (is_null($taa_render_samples)) {
            throw new \InvalidArgumentException('non-nullable taa_render_samples cannot be null');
        }

        if (($taa_render_samples > 256)) {
            throw new \InvalidArgumentException('invalid value for $taa_render_samples when calling JobParametersBlenderEevee., must be smaller than or equal to 256.');
        }
        if (($taa_render_samples < 1)) {
            throw new \InvalidArgumentException('invalid value for $taa_render_samples when calling JobParametersBlenderEevee., must be bigger than or equal to 1.');
        }

        $this->container['taa_render_samples'] = $taa_render_samples;

        return $this;
    }

    /**
     * Gets scene_url
     *
     * @return string
     */
    public function getSceneUrl()
    {
        return $this->container['scene_url'];
    }

    /**
     * Sets scene_url
     *
     * @param string $scene_url scene_url
     *
     * @return self
     */
    public function setSceneUrl($scene_url)
    {
        if (is_null($scene_url)) {
            throw new \InvalidArgumentException('non-nullable scene_url cannot be null');
        }
        $this->container['scene_url'] = $scene_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


