<?php
/**
 * JobType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Acaisia Marketplace Client
 *
 * Endpoints for clients - users that want to submit calculations. E.g. someone running an inference request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Acaisia\Marketplace\Model;
use \Acaisia\Marketplace\ObjectSerializer;

/**
 * JobType Class Doc Comment
 *
 * @category Class
 * @description Type of job that you want to run
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JobType
{
    /**
     * Possible values of this enum
     */
    public const TEXT_TO_TEXT = 'TEXT_TO_TEXT';

    public const TEXT_TO_IMAGE = 'TEXT_TO_IMAGE';

    public const BLENDER_EEVEE = 'BLENDER_EEVEE';

    public const BLENDER_CYCLES = 'BLENDER_CYCLES';

    public const IMAGE_TO_3_D = 'IMAGE_TO_3D';

    public const IMAGE_TO_3_D_V2 = 'IMAGE_TO_3D_V2';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TEXT_TO_TEXT,
            self::TEXT_TO_IMAGE,
            self::BLENDER_EEVEE,
            self::BLENDER_CYCLES,
            self::IMAGE_TO_3_D,
            self::IMAGE_TO_3_D_V2
        ];
    }
}


