<?php
/**
 * ApiKeyUsageTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Acaisia Marketplace Client
 *
 * Endpoints for clients - users that want to submit calculations. E.g. someone running an inference request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Acaisia\Marketplace\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApiKeyUsageTest Class Doc Comment
 *
 * @category    Class
 * @description ApiKeyUsage
 * @package     Acaisia\Marketplace
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiKeyUsageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ApiKeyUsage"
     */
    public function testApiKeyUsage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "jobs"
     */
    public function testPropertyJobs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spent"
     */
    public function testPropertySpent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
