<?php
/**
 * JobsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Acaisia Marketplace Client
 *
 * Endpoints for clients - users that want to submit calculations. E.g. someone running an inference request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Acaisia\Marketplace\Test\Api;

use \Acaisia\Marketplace\Configuration;
use \Acaisia\Marketplace\ApiException;
use \Acaisia\Marketplace\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * JobsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Acaisia\Marketplace
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JobsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createJob
     *
     * Create a new job.
     *
     */
    public function testCreateJob()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getJob
     *
     * Get the status of a specific job.
     *
     */
    public function testGetJob()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listJobs
     *
     * List all jobs.
     *
     */
    public function testListJobs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
